#ifndef WFWFS_REVISION_HPP
#define WFWFS_REVISION_HPP
/***************************************************************************
 *                                                                         *
 *   WFWFS (Wide-field wavefront sensor) software                          *
 *                                                                         *
 *   Copyright (C) 2018-2019 by Tomas Hillberg  <hillberg@astro.su.se>     *
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 *   This program is distributed in the hope that it will be useful,       *
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of        *
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the         *
 *   GNU General Public License for more details.                          *
 *                                                                         *
 *   You should have received a copy of the GNU General Public License     *
 *   along with this program; if not, write to the                         *
 *   Free Software Foundation, Inc.,                                       *
 *   59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.             *
 *                                                                         *
 ***************************************************************************/

namespace wfwfs {
    
    /*!  @ingroup wfwfs
     *  @{
     */

    /*!  @file      revision.hpp
     *   @brief     Constants containing the version numbers and revision details of the binaries.
     *   @name      Version/Revision information
     *   @details   These constants are auto-generated by cmake/git and placed in the \c revision.cpp file.
     *              The version numbers will be extracted from the latest \em annotated label in the git-tree,
     *              and the revision-status will contain the latest commit message (and a tag "Modified" if
     *              the git-tree contains un-commited modifications).
     *
     *   @author    Tomas Hillberg (hillberg@astro.su.se)
     *   @date      2018
     */

    extern const int versionMajor;       //!< Major version
    extern const int versionMinor;       //!< Minor version
    extern const int versionPatch;       //!< Patch version
    extern const int versionCommit;      //!< Number of commits since last version-tag
    extern const char* commitMessage;    //!< Commit message of the last commit
    extern const char* commitTime;       //!< Commit timestamp
    extern const char* buildTime;        //!< Compilation timestamp

    /*! @} */
    
}

#endif // WFWFS_REVISION_HPP
